// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package tom.example.serialize.protobuf;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *无符号整型，有符号的话sint32
     * </pre>
     *
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional bool sex = 3;</code>
     */
    boolean getSex();

    /**
     * <code>optional int64 birthday = 4;</code>
     */
    long getBirthday();

    /**
     * <code>optional string address = 5;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    java.util.List<tom.example.serialize.protobuf.PersonProto.Car> 
        getCarsList();
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    tom.example.serialize.protobuf.PersonProto.Car getCars(int index);
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    int getCarsCount();
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    java.util.List<? extends tom.example.serialize.protobuf.PersonProto.CarOrBuilder> 
        getCarsOrBuilderList();
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    tom.example.serialize.protobuf.PersonProto.CarOrBuilder getCarsOrBuilder(
        int index);

    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    int getOtherCount();
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    boolean containsOther(
        java.lang.String key);
    /**
     * Use {@link #getOtherMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getOther();
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getOtherMap();
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    java.lang.String getOtherOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    java.lang.String getOtherOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *PersonProto的内部类 字段名等号后面的是字段属性标识，不能重复
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      age_ = 0;
      sex_ = false;
      birthday_ = 0L;
      address_ = "";
      cars_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 24: {

              sex_ = input.readBool();
              break;
            }
            case 32: {

              birthday_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                cars_ = new java.util.ArrayList<tom.example.serialize.protobuf.PersonProto.Car>();
                mutable_bitField0_ |= 0x00000020;
              }
              cars_.add(
                  input.readMessage(tom.example.serialize.protobuf.PersonProto.Car.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                other_ = com.google.protobuf.MapField.newMapField(
                    OtherDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              other = input.readMessage(
                  OtherDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              other_.getMutableMap().put(other.getKey(), other.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          cars_ = java.util.Collections.unmodifiableList(cars_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tom.example.serialize.protobuf.PersonProto.internal_static_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetOther();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tom.example.serialize.protobuf.PersonProto.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tom.example.serialize.protobuf.PersonProto.Person.class, tom.example.serialize.protobuf.PersonProto.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     *无符号整型，有符号的话sint32
     * </pre>
     *
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private boolean sex_;
    /**
     * <code>optional bool sex = 3;</code>
     */
    public boolean getSex() {
      return sex_;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 4;
    private long birthday_;
    /**
     * <code>optional int64 birthday = 4;</code>
     */
    public long getBirthday() {
      return birthday_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 5;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARS_FIELD_NUMBER = 6;
    private java.util.List<tom.example.serialize.protobuf.PersonProto.Car> cars_;
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    public java.util.List<tom.example.serialize.protobuf.PersonProto.Car> getCarsList() {
      return cars_;
    }
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    public java.util.List<? extends tom.example.serialize.protobuf.PersonProto.CarOrBuilder> 
        getCarsOrBuilderList() {
      return cars_;
    }
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    public int getCarsCount() {
      return cars_.size();
    }
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    public tom.example.serialize.protobuf.PersonProto.Car getCars(int index) {
      return cars_.get(index);
    }
    /**
     * <pre>
     *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
     *repeated 代表是集合类型
     * </pre>
     *
     * <code>repeated .Car cars = 6;</code>
     */
    public tom.example.serialize.protobuf.PersonProto.CarOrBuilder getCarsOrBuilder(
        int index) {
      return cars_.get(index);
    }

    public static final int OTHER_FIELD_NUMBER = 7;
    private static final class OtherDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  tom.example.serialize.protobuf.PersonProto.internal_static_Person_OtherEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> other_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetOther() {
      if (other_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OtherDefaultEntryHolder.defaultEntry);
      }
      return other_;
    }

    public int getOtherCount() {
      return internalGetOther().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    public boolean containsOther(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetOther().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOtherMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getOther() {
      return getOtherMap();
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getOtherMap() {
      return internalGetOther().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    public java.lang.String getOtherOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOther().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; other = 7;</code>
     */

    public java.lang.String getOtherOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOther().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (sex_ != false) {
        output.writeBool(3, sex_);
      }
      if (birthday_ != 0L) {
        output.writeInt64(4, birthday_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        output.writeMessage(6, cars_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetOther().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        other = OtherDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(7, other);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (sex_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, sex_);
      }
      if (birthday_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, birthday_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      for (int i = 0; i < cars_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, cars_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetOther().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        other = OtherDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, other);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tom.example.serialize.protobuf.PersonProto.Person)) {
        return super.equals(obj);
      }
      tom.example.serialize.protobuf.PersonProto.Person other = (tom.example.serialize.protobuf.PersonProto.Person) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (getSex()
          == other.getSex());
      result = result && (getBirthday()
          == other.getBirthday());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getCarsList()
          .equals(other.getCarsList());
      result = result && internalGetOther().equals(
          other.internalGetOther());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSex());
      hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBirthday());
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      if (getCarsCount() > 0) {
        hash = (37 * hash) + CARS_FIELD_NUMBER;
        hash = (53 * hash) + getCarsList().hashCode();
      }
      if (!internalGetOther().getMap().isEmpty()) {
        hash = (37 * hash) + OTHER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOther().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tom.example.serialize.protobuf.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tom.example.serialize.protobuf.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *PersonProto的内部类 字段名等号后面的是字段属性标识，不能重复
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        tom.example.serialize.protobuf.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tom.example.serialize.protobuf.PersonProto.internal_static_Person_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetOther();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableOther();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tom.example.serialize.protobuf.PersonProto.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tom.example.serialize.protobuf.PersonProto.Person.class, tom.example.serialize.protobuf.PersonProto.Person.Builder.class);
      }

      // Construct using tom.example.serialize.protobuf.PersonProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCarsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        sex_ = false;

        birthday_ = 0L;

        address_ = "";

        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          carsBuilder_.clear();
        }
        internalGetMutableOther().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tom.example.serialize.protobuf.PersonProto.internal_static_Person_descriptor;
      }

      public tom.example.serialize.protobuf.PersonProto.Person getDefaultInstanceForType() {
        return tom.example.serialize.protobuf.PersonProto.Person.getDefaultInstance();
      }

      public tom.example.serialize.protobuf.PersonProto.Person build() {
        tom.example.serialize.protobuf.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tom.example.serialize.protobuf.PersonProto.Person buildPartial() {
        tom.example.serialize.protobuf.PersonProto.Person result = new tom.example.serialize.protobuf.PersonProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.age_ = age_;
        result.sex_ = sex_;
        result.birthday_ = birthday_;
        result.address_ = address_;
        if (carsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            cars_ = java.util.Collections.unmodifiableList(cars_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.cars_ = cars_;
        } else {
          result.cars_ = carsBuilder_.build();
        }
        result.other_ = internalGetOther();
        result.other_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tom.example.serialize.protobuf.PersonProto.Person) {
          return mergeFrom((tom.example.serialize.protobuf.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tom.example.serialize.protobuf.PersonProto.Person other) {
        if (other == tom.example.serialize.protobuf.PersonProto.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getSex() != false) {
          setSex(other.getSex());
        }
        if (other.getBirthday() != 0L) {
          setBirthday(other.getBirthday());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (carsBuilder_ == null) {
          if (!other.cars_.isEmpty()) {
            if (cars_.isEmpty()) {
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureCarsIsMutable();
              cars_.addAll(other.cars_);
            }
            onChanged();
          }
        } else {
          if (!other.cars_.isEmpty()) {
            if (carsBuilder_.isEmpty()) {
              carsBuilder_.dispose();
              carsBuilder_ = null;
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000020);
              carsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCarsFieldBuilder() : null;
            } else {
              carsBuilder_.addAllMessages(other.cars_);
            }
          }
        }
        internalGetMutableOther().mergeFrom(
            other.internalGetOther());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tom.example.serialize.protobuf.PersonProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tom.example.serialize.protobuf.PersonProto.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *声明内部类的属性，及属性类型，属性编号：在同一个message内部是全局唯一的，不能够重复。
       * </pre>
       *
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       *无符号整型，有符号的话sint32
       * </pre>
       *
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       *无符号整型，有符号的话sint32
       * </pre>
       *
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *无符号整型，有符号的话sint32
       * </pre>
       *
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private boolean sex_ ;
      /**
       * <code>optional bool sex = 3;</code>
       */
      public boolean getSex() {
        return sex_;
      }
      /**
       * <code>optional bool sex = 3;</code>
       */
      public Builder setSex(boolean value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool sex = 3;</code>
       */
      public Builder clearSex() {
        
        sex_ = false;
        onChanged();
        return this;
      }

      private long birthday_ ;
      /**
       * <code>optional int64 birthday = 4;</code>
       */
      public long getBirthday() {
        return birthday_;
      }
      /**
       * <code>optional int64 birthday = 4;</code>
       */
      public Builder setBirthday(long value) {
        
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 birthday = 4;</code>
       */
      public Builder clearBirthday() {
        
        birthday_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 5;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.util.List<tom.example.serialize.protobuf.PersonProto.Car> cars_ =
        java.util.Collections.emptyList();
      private void ensureCarsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          cars_ = new java.util.ArrayList<tom.example.serialize.protobuf.PersonProto.Car>(cars_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          tom.example.serialize.protobuf.PersonProto.Car, tom.example.serialize.protobuf.PersonProto.Car.Builder, tom.example.serialize.protobuf.PersonProto.CarOrBuilder> carsBuilder_;

      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public java.util.List<tom.example.serialize.protobuf.PersonProto.Car> getCarsList() {
        if (carsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cars_);
        } else {
          return carsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public int getCarsCount() {
        if (carsBuilder_ == null) {
          return cars_.size();
        } else {
          return carsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public tom.example.serialize.protobuf.PersonProto.Car getCars(int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);
        } else {
          return carsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder setCars(
          int index, tom.example.serialize.protobuf.PersonProto.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.set(index, value);
          onChanged();
        } else {
          carsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder setCars(
          int index, tom.example.serialize.protobuf.PersonProto.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.set(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(tom.example.serialize.protobuf.PersonProto.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(value);
          onChanged();
        } else {
          carsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(
          int index, tom.example.serialize.protobuf.PersonProto.Car value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(index, value);
          onChanged();
        } else {
          carsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(
          tom.example.serialize.protobuf.PersonProto.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addCars(
          int index, tom.example.serialize.protobuf.PersonProto.Car.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder addAllCars(
          java.lang.Iterable<? extends tom.example.serialize.protobuf.PersonProto.Car> values) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cars_);
          onChanged();
        } else {
          carsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder clearCars() {
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          carsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public Builder removeCars(int index) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.remove(index);
          onChanged();
        } else {
          carsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public tom.example.serialize.protobuf.PersonProto.Car.Builder getCarsBuilder(
          int index) {
        return getCarsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public tom.example.serialize.protobuf.PersonProto.CarOrBuilder getCarsOrBuilder(
          int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);  } else {
          return carsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public java.util.List<? extends tom.example.serialize.protobuf.PersonProto.CarOrBuilder> 
           getCarsOrBuilderList() {
        if (carsBuilder_ != null) {
          return carsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cars_);
        }
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public tom.example.serialize.protobuf.PersonProto.Car.Builder addCarsBuilder() {
        return getCarsFieldBuilder().addBuilder(
            tom.example.serialize.protobuf.PersonProto.Car.getDefaultInstance());
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public tom.example.serialize.protobuf.PersonProto.Car.Builder addCarsBuilder(
          int index) {
        return getCarsFieldBuilder().addBuilder(
            index, tom.example.serialize.protobuf.PersonProto.Car.getDefaultInstance());
      }
      /**
       * <pre>
       *required、optional、repeated标注存在着3中，在3.0之前，标注是必须的，但在3.0之后required、optional是可以不写的
       *repeated 代表是集合类型
       * </pre>
       *
       * <code>repeated .Car cars = 6;</code>
       */
      public java.util.List<tom.example.serialize.protobuf.PersonProto.Car.Builder> 
           getCarsBuilderList() {
        return getCarsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          tom.example.serialize.protobuf.PersonProto.Car, tom.example.serialize.protobuf.PersonProto.Car.Builder, tom.example.serialize.protobuf.PersonProto.CarOrBuilder> 
          getCarsFieldBuilder() {
        if (carsBuilder_ == null) {
          carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              tom.example.serialize.protobuf.PersonProto.Car, tom.example.serialize.protobuf.PersonProto.Car.Builder, tom.example.serialize.protobuf.PersonProto.CarOrBuilder>(
                  cars_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          cars_ = null;
        }
        return carsBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> other_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetOther() {
        if (other_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OtherDefaultEntryHolder.defaultEntry);
        }
        return other_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableOther() {
        onChanged();;
        if (other_ == null) {
          other_ = com.google.protobuf.MapField.newMapField(
              OtherDefaultEntryHolder.defaultEntry);
        }
        if (!other_.isMutable()) {
          other_ = other_.copy();
        }
        return other_;
      }

      public int getOtherCount() {
        return internalGetOther().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public boolean containsOther(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetOther().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOtherMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getOther() {
        return getOtherMap();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getOtherMap() {
        return internalGetOther().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public java.lang.String getOtherOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetOther().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public java.lang.String getOtherOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetOther().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOther() {
        getMutableOther().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public Builder removeOther(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableOther().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableOther() {
        return internalGetMutableOther().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */
      public Builder putOther(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableOther().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; other = 7;</code>
       */

      public Builder putAllOther(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableOther().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final tom.example.serialize.protobuf.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tom.example.serialize.protobuf.PersonProto.Person();
    }

    public static tom.example.serialize.protobuf.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public tom.example.serialize.protobuf.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string color = 2;</code>
     */
    java.lang.String getColor();
    /**
     * <code>optional string color = 2;</code>
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>optional string engine = 3;</code>
     */
    java.lang.String getEngine();
    /**
     * <code>optional string engine = 3;</code>
     */
    com.google.protobuf.ByteString
        getEngineBytes();

    /**
     * <pre>
     *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
     * </pre>
     *
     * <code>optional string plate_number = 4;</code>
     */
    java.lang.String getPlateNumber();
    /**
     * <pre>
     *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
     * </pre>
     *
     * <code>optional string plate_number = 4;</code>
     */
    com.google.protobuf.ByteString
        getPlateNumberBytes();

    /**
     * <code>optional double price = 5;</code>
     */
    double getPrice();
  }
  /**
   * Protobuf type {@code Car}
   */
  public  static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Car)
      CarOrBuilder {
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      name_ = "";
      color_ = "";
      engine_ = "";
      plateNumber_ = "";
      price_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              color_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              engine_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              plateNumber_ = s;
              break;
            }
            case 41: {

              price_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tom.example.serialize.protobuf.PersonProto.internal_static_Car_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tom.example.serialize.protobuf.PersonProto.internal_static_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tom.example.serialize.protobuf.PersonProto.Car.class, tom.example.serialize.protobuf.PersonProto.Car.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object color_;
    /**
     * <code>optional string color = 2;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>optional string color = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENGINE_FIELD_NUMBER = 3;
    private volatile java.lang.Object engine_;
    /**
     * <code>optional string engine = 3;</code>
     */
    public java.lang.String getEngine() {
      java.lang.Object ref = engine_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engine_ = s;
        return s;
      }
    }
    /**
     * <code>optional string engine = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEngineBytes() {
      java.lang.Object ref = engine_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATE_NUMBER_FIELD_NUMBER = 4;
    private volatile java.lang.Object plateNumber_;
    /**
     * <pre>
     *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
     * </pre>
     *
     * <code>optional string plate_number = 4;</code>
     */
    public java.lang.String getPlateNumber() {
      java.lang.Object ref = plateNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plateNumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
     * </pre>
     *
     * <code>optional string plate_number = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPlateNumberBytes() {
      java.lang.Object ref = plateNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plateNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 5;
    private double price_;
    /**
     * <code>optional double price = 5;</code>
     */
    public double getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getColorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, color_);
      }
      if (!getEngineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, engine_);
      }
      if (!getPlateNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, plateNumber_);
      }
      if (price_ != 0D) {
        output.writeDouble(5, price_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getColorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, color_);
      }
      if (!getEngineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, engine_);
      }
      if (!getPlateNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, plateNumber_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, price_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tom.example.serialize.protobuf.PersonProto.Car)) {
        return super.equals(obj);
      }
      tom.example.serialize.protobuf.PersonProto.Car other = (tom.example.serialize.protobuf.PersonProto.Car) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getColor()
          .equals(other.getColor());
      result = result && getEngine()
          .equals(other.getEngine());
      result = result && getPlateNumber()
          .equals(other.getPlateNumber());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (37 * hash) + ENGINE_FIELD_NUMBER;
      hash = (53 * hash) + getEngine().hashCode();
      hash = (37 * hash) + PLATE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPlateNumber().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tom.example.serialize.protobuf.PersonProto.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tom.example.serialize.protobuf.PersonProto.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Car)
        tom.example.serialize.protobuf.PersonProto.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tom.example.serialize.protobuf.PersonProto.internal_static_Car_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tom.example.serialize.protobuf.PersonProto.internal_static_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tom.example.serialize.protobuf.PersonProto.Car.class, tom.example.serialize.protobuf.PersonProto.Car.Builder.class);
      }

      // Construct using tom.example.serialize.protobuf.PersonProto.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        color_ = "";

        engine_ = "";

        plateNumber_ = "";

        price_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tom.example.serialize.protobuf.PersonProto.internal_static_Car_descriptor;
      }

      public tom.example.serialize.protobuf.PersonProto.Car getDefaultInstanceForType() {
        return tom.example.serialize.protobuf.PersonProto.Car.getDefaultInstance();
      }

      public tom.example.serialize.protobuf.PersonProto.Car build() {
        tom.example.serialize.protobuf.PersonProto.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tom.example.serialize.protobuf.PersonProto.Car buildPartial() {
        tom.example.serialize.protobuf.PersonProto.Car result = new tom.example.serialize.protobuf.PersonProto.Car(this);
        result.name_ = name_;
        result.color_ = color_;
        result.engine_ = engine_;
        result.plateNumber_ = plateNumber_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tom.example.serialize.protobuf.PersonProto.Car) {
          return mergeFrom((tom.example.serialize.protobuf.PersonProto.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tom.example.serialize.protobuf.PersonProto.Car other) {
        if (other == tom.example.serialize.protobuf.PersonProto.Car.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          onChanged();
        }
        if (!other.getEngine().isEmpty()) {
          engine_ = other.engine_;
          onChanged();
        }
        if (!other.getPlateNumber().isEmpty()) {
          plateNumber_ = other.plateNumber_;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tom.example.serialize.protobuf.PersonProto.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tom.example.serialize.protobuf.PersonProto.Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object color_ = "";
      /**
       * <code>optional string color = 2;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public Builder clearColor() {
        
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string color = 2;</code>
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        color_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object engine_ = "";
      /**
       * <code>optional string engine = 3;</code>
       */
      public java.lang.String getEngine() {
        java.lang.Object ref = engine_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          engine_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string engine = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEngineBytes() {
        java.lang.Object ref = engine_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          engine_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string engine = 3;</code>
       */
      public Builder setEngine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        engine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string engine = 3;</code>
       */
      public Builder clearEngine() {
        
        engine_ = getDefaultInstance().getEngine();
        onChanged();
        return this;
      }
      /**
       * <code>optional string engine = 3;</code>
       */
      public Builder setEngineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        engine_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object plateNumber_ = "";
      /**
       * <pre>
       *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
       * </pre>
       *
       * <code>optional string plate_number = 4;</code>
       */
      public java.lang.String getPlateNumber() {
        java.lang.Object ref = plateNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          plateNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
       * </pre>
       *
       * <code>optional string plate_number = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPlateNumberBytes() {
        java.lang.Object ref = plateNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          plateNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
       * </pre>
       *
       * <code>optional string plate_number = 4;</code>
       */
      public Builder setPlateNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        plateNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
       * </pre>
       *
       * <code>optional string plate_number = 4;</code>
       */
      public Builder clearPlateNumber() {
        
        plateNumber_ = getDefaultInstance().getPlateNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *车牌号，使用下划线命名，在java类中会转换为驼峰命名的
       * </pre>
       *
       * <code>optional string plate_number = 4;</code>
       */
      public Builder setPlateNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        plateNumber_ = value;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 5;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 5;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 5;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Car)
    }

    // @@protoc_insertion_point(class_scope:Car)
    private static final tom.example.serialize.protobuf.PersonProto.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tom.example.serialize.protobuf.PersonProto.Car();
    }

    public static tom.example.serialize.protobuf.PersonProto.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    public tom.example.serialize.protobuf.PersonProto.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_OtherEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_OtherEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\"\270\001\n\006Person\022\014\n\004name\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\005\022\013\n\003sex\030\003 \001(\010\022\020\n\010birthday\030\004" +
      " \001(\003\022\017\n\007address\030\005 \001(\t\022\022\n\004cars\030\006 \003(\0132\004.Ca" +
      "r\022!\n\005other\030\007 \003(\0132\022.Person.OtherEntry\032,\n\n" +
      "OtherEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\"W\n\003Car\022\014\n\004name\030\001 \001(\t\022\r\n\005color\030\002 \001(\t\022\016" +
      "\n\006engine\030\003 \001(\t\022\024\n\014plate_number\030\004 \001(\t\022\r\n\005" +
      "price\030\005 \001(\001B-\n\036tom.example.serialize.pro" +
      "tobufB\013PersonProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Sex", "Birthday", "Address", "Cars", "Other", });
    internal_static_Person_OtherEntry_descriptor =
      internal_static_Person_descriptor.getNestedTypes().get(0);
    internal_static_Person_OtherEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_OtherEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Car_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Car_descriptor,
        new java.lang.String[] { "Name", "Color", "Engine", "PlateNumber", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
